/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-surface': '#191c1e',
        'on-surface-variant': '#45474c',
        'background': '#f7f9fc',
        'primary-container': '#101c2e',
        'primary': '#000000',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'surface': '#f7f9fc',
        'surface-variant': '#e0e3e6',
        'on-tertiary-container': '#7484a6',
        'outline': '#75777d',
        'secondary': '#755b00',
        'tertiary-fixed-dim': '#b6c7ec',
        'on-tertiary-fixed': '#081b38',
        'on-background': '#191c1e',
        'on-primary-fixed-variant': '#3c475b',
        'outline-variant': '#c5c6cd',
        'on-primary': '#ffffff',
        'on-primary-container': '#79849b',
        'secondary-container': '#fed977',
        'on-secondary-container': '#785d00',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eff1f4',
        'surface-container-low': '#f2f4f7',
        'surface-container': '#eceef1',
        'surface-container-high': '#e6e8eb',
        'on-secondary': '#ffffff',
        'tertiary-container': '#081b38',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
